### ISSUE TITLE
Worker threads/processes

### ISSUE THREAD

**Issue by bkeroackdsc** [dollarshaveclub/fastboot-docker#3]
@pwfisher @arjansingh 

a) Are you running multiple HTTP listener threads/processes?
b) if so, can you expose a way to toggle the number of worker threads/processes at runtime via environment variable?

**Comment by pwfisher** [comment]
`fastboot-app-server` [defaults to one worker per CPU](https://github.com/ember-fastboot/fastboot-app-server/blob/500c29a/src/fastboot-app-server.js#L41). This is configurable and we can expose it.
